# OpenStreetMap POI categories and subtypes
# Based on OSM documentation: https://wiki.openstreetmap.org/wiki/Map_features

POI_CATEGORIES = {
    "amenity": [
        # Sustenance
        "bar",
        "biergarten",
        "cafe",
        "fast_food",
        "food_court",
        "ice_cream",
        "pub",
        "restaurant",
        # Education
        "college",
        "driving_school",
        "kindergarten",
        "language_school",
        "library",
        "school",
        "university",
        # Transportation
        "bicycle_parking",
        "bicycle_rental",
        "bus_station",
        "car_rental",
        "car_sharing",
        "car_wash",
        "charging_station",
        "ferry_terminal",
        "fuel",
        "parking",
        "parking_space",
        "taxi",
        # Financial
        "atm",
        "bank",
        "bureau_de_change",
        # Healthcare
        "clinic",
        "dentist",
        "doctors",
        "hospital",
        "nursing_home",
        "pharmacy",
        "veterinary",
        # Entertainment and Arts
        "arts_centre",
        "casino",
        "cinema",
        "community_centre",
        "fountain",
        "nightclub",
        "planetarium",
        "theatre",
        # Others
        "courthouse",
        "fire_station",
        "police",
        "post_box",
        "post_office",
        "prison",
        "public_bath",
        "townhall",
        "marketplace",
        "place_of_worship",
        "toilets",
    ],
    "tourism": [
        "alpine_hut",
        "apartment",
        "attraction",
        "camp_site",
        "caravan_site",
        "chalet",
        "gallery",
        "guest_house",
        "hostel",
        "hotel",
        "information",
        "motel",
        "museum",
        "picnic_site",
        "theme_park",
        "viewpoint",
        "zoo",
    ],
    "leisure": [
        "beach_resort",
        "bird_hide",
        "dog_park",
        "fitness_centre",
        "garden",
        "golf_course",
        "ice_rink",
        "marina",
        "nature_reserve",
        "park",
        "playground",
        "sports_centre",
        "stadium",
        "swimming_pool",
        "track",
        "water_park",
    ],
    "historic": [
        "archaeological_site",
        "battlefield",
        "boundary_stone",
        "building",
        "castle",
        "church",
        "city_gate",
        "citywalls",
        "fort",
        "manor",
        "memorial",
        "monument",
        "ruins",
        "ship",
        "tomb",
        "wayside_cross",
        "wayside_shrine",
    ],
    "natural": [
        "bay",
        "beach",
        "cape",
        "cave_entrance",
        "cliff",
        "crater",
        "fell",
        "glacier",
        "heath",
        "hill",
        "island",
        "land",
        "marsh",
        "moor",
        "mud",
        "peak",
        "reef",
        "ridge",
        "rock",
        "sand",
        "scree",
        "scrub",
        "spring",
        "stone",
        "tree",
        "valley",
        "volcano",
        "water",
        "wetland",
        "wood",
    ],
    "shop": [
        # Food, beverages
        "alcohol",
        "bakery",
        "beverages",
        "butcher",
        "cheese",
        "chocolate",
        "coffee",
        "confectionery",
        "convenience",
        "deli",
        "dairy",
        "farm",
        "greengrocer",
        "health_food",
        "ice_cream",
        "pasta",
        "pastry",
        "seafood",
        "spices",
        "supermarket",
        "tea",
        "wine",
        # General retail
        "department_store",
        "general",
        "kiosk",
        "mall",
        "wholesale",
        # Clothing, shoes, accessories
        "baby_goods",
        "bag",
        "boutique",
        "clothes",
        "fabric",
        "fashion",
        "jewelry",
        "leather",
        "shoes",
        "tailor",
        "watches",
        # Household
        "bathroom_furnishing",
        "carpet",
        "curtain",
        "doityourself",
        "electrical",
        "florist",
        "furniture",
        "garden_centre",
        "hardware",
        "houseware",
        "locksmith",
        "paint",
        "trade",
        # Electronics
        "computer",
        "electronics",
        "mobile_phone",
        "vacuum_cleaner",
        # Outdoors and sport
        "bicycle",
        "car",
        "car_repair",
        "car_parts",
        "fishing",
        "free_flying",
        "hunting",
        "motorcycle",
        "outdoor",
        "scuba_diving",
        "ski",
        "sports",
        "swimming_pool",
        "tyres",
        # Art, music, hobbies
        "art",
        "craft",
        "frame",
        "games",
        "model",
        "music",
        "musical_instrument",
        "photo",
        "camera",
        "trophy",
        "video",
        "video_games",
        # Others
        "books",
        "gift",
        "lottery",
        "newsagent",
        "stationery",
        "ticket",
    ],
}
